### ISSUE TITLE
Maven run-time utilizing Maven Wrapper

### ISSUE THREAD

**Issue by dlehammer** [robinst/git-merge-repos#12]
The maven version isn't specified in the [Dependencies](https://github.com/robinst/git-merge-repos#dependencies)-section in the documentation.
This is a potential risk, as the current implementation might not be compatible with new Maven releases.

I suggest encapsulating this in the code, by utilizing the [Maven Wrapper](https://github.com/takari/maven-wrapper#maven-wrapper) a.k.a. ```mvnw```.
Hence no need to document or force the user to setup a environment for a specific Maven-version, instead this is handled implicitly :-)

**Comment by robinst** [comment]
Sounds like a good idea. Do you want to raise a pull request to change it?

**Comment by dlehammer** [comment]
@robinst my initial idea was that the maintainer probably knows what Maven version was last used - and by utilizing the Maven Wrapper there wouldn't be any need to document outside of the mvnw-configuration.

Unfortunately I don't know either tool well enough to provide a pull request.
But I'll be happy to assist with testing.

**Comment by robinst** [comment]
Ok. I'm just gonna leave this open then, if someone wants to do it I'm open to pull requests.

**Comment by dlehammer** [comment]
@robinst perhaps you're able to remember the last Maven version used for this project?
(include it here)

So whoever takes a crack at mvnw, does so with a compatible version :)

**Comment by robinst** [comment]
Should be compatible with the newest version, or we can make it compatible. Doesn't really use anything fancy :).
