### ISSUE TITLE
dash-support in new sub-directory name for "Preserve History for Paths"

### ISSUE THREAD

**Issue by dlehammer** [robinst/git-merge-repos#13]
The current ```git filter-branch``` approach described in [Preserve History for Paths](https://github.com/robinst/git-merge-repos#preserve-history-for-paths) doesn't support remapping to from ex. "subdir" to "new-subdir".

I've found the following syntax supports dash 
```
git filter-branch --index-filter \
  'tab=$(printf "\t") && git ls-files -s --error-unmatch . >/dev/null 2>&1; [ $? != 0 ] || (git ls-files -s | sed "s~$tab\"*~&new-subdir/~" | GIT_INDEX_FILE=$GIT_INDEX_FILE.new git update-index --index-info && mv "$GIT_INDEX_FILE.new" "$GIT_INDEX_FILE")' \
  --tag-name-filter cat \
  -- --all
```

**Comment by robinst** [comment]
Thanks, fixed! Feel free to raise a pull request next time :).
