### ISSUE TITLE
git@bitbucket.org auth failed with valid ssh keys

### ISSUE THREAD

**Issue by black-inc-service** [robinst/git-merge-repos#20]
Java: 17 LTS
Maven: 3.8.7

From the terminal
`git clone git@bitbucket.org:company/repo1.git`
`git clone git@bitbucket.org:company/repo2.git`
works fine

However:
`./run.sh git@bitbucket.org:company/repo1.git:aa git@bitbucket.org:company/repo2.git:bb`

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (default-cli) on project git-merge-repos: An exception occured while executing the Java class. null: InvocationTargetException: Invalid remote: git@bitbucket.org: git@bitbucket.org: Auth fail. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I have valid ssh keys in ~/.ssh

**Comment by black-inc-service** [comment]
Looks like only classic OpenSSH keys are allowed, the documentation should state this.

**Comment by robinst** [comment]
Hey @black-inc-service! I've just bumped the version of JGit, I wonder if that fixes your problem? Could you try again and report back?
