### ISSUE TITLE
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project git-merge-repos: An exception occured while executing the Java class. null: InvocationTargetException: Invalid remote

### ISSUE THREAD

**Issue by cssensei** [robinst/git-merge-repos#5]
Hello @robinst!
I'm trying to merge 2 distinct repositories and although the command for preserving the history for paths worked well, I'm hitting the error in the title. I've attached a debug image with my terminal. Any idea what could be the fix for this?
Thank you!

![image](https://cloud.githubusercontent.com/assets/1344020/8981314/9812ad5a-36b7-11e5-8968-9f0b8d54480f.png)

**Comment by cssensei** [comment]
Stupid me... Apparently the scripts doesn't work with relative paths. I had to use the absolute paths and all it's ok now. Thanks, anyway!

**Comment by robinst** [comment]
Relative paths are a bit of a pain to make work with the wrapper script. I made it a bit more clear in the instructions now, thanks for reporting!

**Comment by cssensei** [comment]
No problem. I'll help anytime when possible!
