### ISSUE TITLE
Exception thrown on .gitignore file

### ISSUE THREAD

**Issue by JohanTan** [robinst/git-merge-repos#8]
I ran the command like this:
`~/git-merge-repos/run.sh git@github.com:orgA/projA.git:. git@github.com:orgA/projB.git:./sites/all`

And this appears after a couple of minutes:
`[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (default-cli) on project git-merge-repos: An exception occured while executing the Java class. null: InvocationTargetException: Invalid path: ./sites/all/.gitignore: invalid name '.' -> [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

Anything I can do to resolve this?

**Comment by robinst** [comment]
Can you try running it like this instead?:

     ~/git-merge-repos/run.sh git@github.com:orgA/projA.git:. git@github.com:orgA/projB.git:sites/all
