### ISSUE TITLE
merge all branches

### ISSUE THREAD

**Issue by silb78** [robinst/git-merge-repos#9]
i have a Repo TestA with 3 branches: master, extension, extension2 and a Repo TestB with 1 branch master.
It's possible to copy/merge the branches extension and extension2 the new merged-repo?

**Comment by robinst** [comment]
Yes, it's possible. What you can do is go into the new repository, and add the old repository "TestA" as a remote, fetch from it, and then create a branch based on the old branch. Something like this:

```
git remote add old ../TestA
git fetch old
git branch extension old/extension
```

Does that help?

**Comment by ssbarnea** [comment]
While I was looking to implement almost the same kind of monorepo merger I ended up with this script: https://github.com/ssbarnea/monorepo/blob/master/git-monorepo-add.sh

Have a look at it, it may help.

**Comment by robinst** [comment]
Thanks @ssbarnea, that might help as well.
